object ModalShadow: TModalShadow
  Left = 0
  Top = 0
  BorderStyle = bsNone
  Caption = 'ModalShadow'
  ClientHeight = 338
  ClientWidth = 651
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Tahoma'
  Font.Style = []
  OldCreateOrder = False
  Scaled = False
  OnClick = FormClick
  PixelsPerInch = 96
  TextHeight = 13
end
