unit Constants.ParNames;

interface

const
  kParNameCount = 68;

type
  TVstParIndex = record
  const
    VoiceMode = 0;
    VoiceGlide = 1;
    PitchTracking = 2;
    SamplePlaybackType = 3;
    SampleResetClockSource = 4;
    SamplerLoopBounds = 5;
    SamplerLoopMode = 6;
    GrainLoop = 7;
    GrainLength = 8;
    GrainRate = 9;
    GrainPosition = 10;
    OutputGain = 11;
    OutputPan = 12;
    VoicePitchOne = 13;
    VoicePitchTwo = 14;
    AuxALevel = 15;
    AuxBLevel = 16;
    OscShape = 17;
    OscPulseWidth = 18;
    NoiseLevel = 19;
    SampleStart = 20;
    SampleEnd = 21;
    LoopStart = 22;
    LoopEnd = 23;
    AmpAttack = 24;
    AmpHold = 25;
    AmpDecay = 26;
    AmpSustain = 27;
    AmpRelease = 28;
    AmpVelocity = 29;
    FilterAttack = 30;
    FilterHold = 31;
    FilterDecay = 32;
    FilterSustain = 33;
    FilterRelease = 34;
    FilterVelocity = 35;
    FilterRouting = 36;
    FilterOutputBlend = 37;
    Filter1Type = 38;
    Filter2Type = 39;
    Filter1KeyFollow = 40;
    Filter2KeyFollow = 41;
    Filter1Par1 = 42;
    Filter1Par2 = 43;
    Filter1Par3 = 44;
    Filter1Par4 = 45;
    Filter2Par1 = 46;
    Filter2Par2 = 47;
    Filter2Par3 = 48;
    Filter2Par4 = 49;
    Lfo1Shape = 50;
    Lfo2Shape = 51;
    Lfo1FreqMode = 52;
    Lfo2FreqMode = 53;
    Lfo1Par1 = 54;
    Lfo1Par2 = 55;
    Lfo1Par3 = 56;
    Lfo2Par1 = 57;
    Lfo2Par2 = 58;
    Lfo2Par3 = 59;
    Seq1Clock = 60;
    Seq1Direction = 61;
    Seq1Length = 62;
    Seq2Clock = 63;
    Seq2Direction = 64;
    Seq2Length = 65;
    PreviewVolume = 66;
    Preview = 67;
  end;

  TVstParName = record
  const
    VoiceMode = 'VoiceMode';
    VoiceGlide = 'VoiceGlide';
    PitchTracking = 'PitchTracking';
    SamplePlaybackType = 'SamplePlaybackType';
    SampleResetClockSource = 'SampleResetClockSource';
    SamplerLoopBounds = 'SamplerLoopBounds';
    SamplerLoopMode = 'SamplerLoopMode';
    GrainLoop = 'GrainLoop';
    GrainLength = 'GrainLength';
    GrainRate = 'GrainRate';
    GrainPosition = 'GrainPosition';
    OutputGain = 'OutputGain';
    OutputPan = 'OutputPan';
    VoicePitchOne = 'VoicePitchOne';
    VoicePitchTwo = 'VoicePitchTwo';
    AuxALevel = 'AuxALevel';
    AuxBLevel = 'AuxBLevel';
    OscShape = 'OscShape';
    OscPulseWidth = 'OscPulseWidth';
    NoiseLevel = 'NoiseLevel';
    SampleStart = 'SampleStart';
    SampleEnd = 'SampleEnd';
    LoopStart = 'LoopStart';
    LoopEnd = 'LoopEnd';
    AmpAttack = 'AmpAttack';
    AmpHold = 'AmpHold';
    AmpDecay = 'AmpDecay';
    AmpSustain = 'AmpSustain';
    AmpRelease = 'AmpRelease';
    AmpVelocity = 'AmpVelocity';
    FilterAttack = 'FilterAttack';
    FilterHold = 'FilterHold';
    FilterDecay = 'FilterDecay';
    FilterSustain = 'FilterSustain';
    FilterRelease = 'FilterRelease';
    FilterVelocity = 'FilterVelocity';
    FilterRouting = 'FilterRouting';
    FilterOutputBlend = 'FilterOutputBlend';
    Filter1Type = 'Filter1Type';
    Filter2Type = 'Filter2Type';
    Filter1KeyFollow = 'Filter1KeyFollow';
    Filter2KeyFollow = 'Filter2KeyFollow';
    Filter1Par1 = 'Filter1Par1';
    Filter1Par2 = 'Filter1Par2';
    Filter1Par3 = 'Filter1Par3';
    Filter1Par4 = 'Filter1Par4';
    Filter2Par1 = 'Filter2Par1';
    Filter2Par2 = 'Filter2Par2';
    Filter2Par3 = 'Filter2Par3';
    Filter2Par4 = 'Filter2Par4';
    Lfo1Shape = 'Lfo1Shape';
    Lfo2Shape = 'Lfo2Shape';
    Lfo1FreqMode = 'Lfo1FreqMode';
    Lfo2FreqMode = 'Lfo2FreqMode';
    Lfo1Par1 = 'Lfo1Par1';
    Lfo1Par2 = 'Lfo1Par2';
    Lfo1Par3 = 'Lfo1Par3';
    Lfo2Par1 = 'Lfo2Par1';
    Lfo2Par2 = 'Lfo2Par2';
    Lfo2Par3 = 'Lfo2Par3';
    Seq1Clock = 'Seq1Clock';
    Seq1Direction = 'Seq1Direction';
    Seq1Length = 'Seq1Length';
    Seq2Clock = 'Seq2Clock';
    Seq2Direction = 'Seq2Direction';
    Seq2Length = 'Seq2Length';
    PreviewVolume = 'PreviewVolume';
    Preview = 'Preview';
  end;

function ParNameToParIndex(const Name : string):integer;
function ParIndexToParName(const Index : integer):string;




implementation


function ParNameToParIndex(const Name : string):integer;
begin
  if Name = 'VoiceMode' then exit(0);
  if Name = 'VoiceGlide' then exit(1);
  if Name = 'PitchTracking' then exit(2);
  if Name = 'SamplePlaybackType' then exit(3);
  if Name = 'SampleResetClockSource' then exit(4);
  if Name = 'SamplerLoopBounds' then exit(5);
  if Name = 'SamplerLoopMode' then exit(6);
  if Name = 'GrainLoop' then exit(7);
  if Name = 'GrainLength' then exit(8);
  if Name = 'GrainRate' then exit(9);
  if Name = 'GrainPosition' then exit(10);
  if Name = 'OutputGain' then exit(11);
  if Name = 'OutputPan' then exit(12);
  if Name = 'VoicePitchOne' then exit(13);
  if Name = 'VoicePitchTwo' then exit(14);
  if Name = 'AuxALevel' then exit(15);
  if Name = 'AuxBLevel' then exit(16);
  if Name = 'OscShape' then exit(17);
  if Name = 'OscPulseWidth' then exit(18);
  if Name = 'NoiseLevel' then exit(19);
  if Name = 'SampleStart' then exit(20);
  if Name = 'SampleEnd' then exit(21);
  if Name = 'LoopStart' then exit(22);
  if Name = 'LoopEnd' then exit(23);
  if Name = 'AmpAttack' then exit(24);
  if Name = 'AmpHold' then exit(25);
  if Name = 'AmpDecay' then exit(26);
  if Name = 'AmpSustain' then exit(27);
  if Name = 'AmpRelease' then exit(28);
  if Name = 'AmpVelocity' then exit(29);
  if Name = 'FilterAttack' then exit(30);
  if Name = 'FilterHold' then exit(31);
  if Name = 'FilterDecay' then exit(32);
  if Name = 'FilterSustain' then exit(33);
  if Name = 'FilterRelease' then exit(34);
  if Name = 'FilterVelocity' then exit(35);
  if Name = 'FilterRouting' then exit(36);
  if Name = 'FilterOutputBlend' then exit(37);
  if Name = 'Filter1Type' then exit(38);
  if Name = 'Filter2Type' then exit(39);
  if Name = 'Filter1KeyFollow' then exit(40);
  if Name = 'Filter2KeyFollow' then exit(41);
  if Name = 'Filter1Par1' then exit(42);
  if Name = 'Filter1Par2' then exit(43);
  if Name = 'Filter1Par3' then exit(44);
  if Name = 'Filter1Par4' then exit(45);
  if Name = 'Filter2Par1' then exit(46);
  if Name = 'Filter2Par2' then exit(47);
  if Name = 'Filter2Par3' then exit(48);
  if Name = 'Filter2Par4' then exit(49);
  if Name = 'Lfo1Shape' then exit(50);
  if Name = 'Lfo2Shape' then exit(51);
  if Name = 'Lfo1FreqMode' then exit(52);
  if Name = 'Lfo2FreqMode' then exit(53);
  if Name = 'Lfo1Par1' then exit(54);
  if Name = 'Lfo1Par2' then exit(55);
  if Name = 'Lfo1Par3' then exit(56);
  if Name = 'Lfo2Par1' then exit(57);
  if Name = 'Lfo2Par2' then exit(58);
  if Name = 'Lfo2Par3' then exit(59);
  if Name = 'Seq1Clock' then exit(60);
  if Name = 'Seq1Direction' then exit(61);
  if Name = 'Seq1Length' then exit(62);
  if Name = 'Seq2Clock' then exit(63);
  if Name = 'Seq2Direction' then exit(64);
  if Name = 'Seq2Length' then exit(65);
  if Name = 'PreviewVolume' then exit(66);
  if Name = 'Preview' then exit(67);
  result := -1;
end;

function ParIndexToParName(const Index : integer):string;
begin
  case Index of
    0: result := 'VoiceMode';
    1: result := 'VoiceGlide';
    2: result := 'PitchTracking';
    3: result := 'SamplePlaybackType';
    4: result := 'SampleResetClockSource';
    5: result := 'SamplerLoopBounds';
    6: result := 'SamplerLoopMode';
    7: result := 'GrainLoop';
    8: result := 'GrainLength';
    9: result := 'GrainRate';
    10: result := 'GrainPosition';
    11: result := 'OutputGain';
    12: result := 'OutputPan';
    13: result := 'VoicePitchOne';
    14: result := 'VoicePitchTwo';
    15: result := 'AuxALevel';
    16: result := 'AuxBLevel';
    17: result := 'OscShape';
    18: result := 'OscPulseWidth';
    19: result := 'NoiseLevel';
    20: result := 'SampleStart';
    21: result := 'SampleEnd';
    22: result := 'LoopStart';
    23: result := 'LoopEnd';
    24: result := 'AmpAttack';
    25: result := 'AmpHold';
    26: result := 'AmpDecay';
    27: result := 'AmpSustain';
    28: result := 'AmpRelease';
    29: result := 'AmpVelocity';
    30: result := 'FilterAttack';
    31: result := 'FilterHold';
    32: result := 'FilterDecay';
    33: result := 'FilterSustain';
    34: result := 'FilterRelease';
    35: result := 'FilterVelocity';
    36: result := 'FilterRouting';
    37: result := 'FilterOutputBlend';
    38: result := 'Filter1Type';
    39: result := 'Filter2Type';
    40: result := 'Filter1KeyFollow';
    41: result := 'Filter2KeyFollow';
    42: result := 'Filter1Par1';
    43: result := 'Filter1Par2';
    44: result := 'Filter1Par3';
    45: result := 'Filter1Par4';
    46: result := 'Filter2Par1';
    47: result := 'Filter2Par2';
    48: result := 'Filter2Par3';
    49: result := 'Filter2Par4';
    50: result := 'Lfo1Shape';
    51: result := 'Lfo2Shape';
    52: result := 'Lfo1FreqMode';
    53: result := 'Lfo2FreqMode';
    54: result := 'Lfo1Par1';
    55: result := 'Lfo1Par2';
    56: result := 'Lfo1Par3';
    57: result := 'Lfo2Par1';
    58: result := 'Lfo2Par2';
    59: result := 'Lfo2Par3';
    60: result := 'Seq1Clock';
    61: result := 'Seq1Direction';
    62: result := 'Seq1Length';
    63: result := 'Seq2Clock';
    64: result := 'Seq2Direction';
    65: result := 'Seq2Length';
    66: result := 'PreviewVolume';
    67: result := 'Preview';
  else
    result := ''
  end;
end;

end.
