{ *********************************************************** }
{ *                    ksTools Library                      * }
{ *       Copyright (c) Sergey Kasandrov 1997, 2009         * }
{ *       -----------------------------------------         * }
{ *         http://sergworks.wordpress.com/kstools          * }
{ *********************************************************** }


{$IFDEF VER120}      // Delphi 4.0
  {$DEFINE OldVersion}
{$ENDIF}

{$IFDEF VER130}      // Delphi 5.0
  {$DEFINE OldVersion}
{$ENDIF}

{$IFDEF VER140}      // Delphi 6.0
  {$DEFINE OldVersion}
{$ENDIF}

{$IFDEF VER150}      // Delphi 7.0
  {$DEFINE OldVersion}
{$ENDIF}

{$IFDEF VER170}      // Delphi 9.0
  {$DEFINE OldVersion}
{$ENDIF}

{$IFDEF VER180}      // Delphi 10.0
  {$DEFINE OldVersion}
{$ENDIF}

{$IFDEF VER185}      // Delphi 11.0
  {$DEFINE OldVersion}
{$ENDIF}

{$IFDEF VER190}      // Delphi 11.0
  {$DEFINE OldVersion}
{$ENDIF}
